USE [master]
GO

CREATE LOGIN [Admin] WITH PASSWORD=N'Tigrou007', DEFAULT_DATABASE=[examenJuin], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
ALTER SERVER ROLE [sysadmin] ADD MEMBER [Admin]
GO


USE [examenJuin]
GO

CREATE USER [Admin] FOR LOGIN [Admin] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_owner] ADD MEMBER [Admin]
GO