USE [master]
GO

CREATE LOGIN [NoRight] WITH PASSWORD=N'Tigrou007', DEFAULT_DATABASE=[examenJuin], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

USE [examenJuin]
GO
CREATE USER [NoRight] FOR LOGIN [NoRight] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_datareader] ADD MEMBER [NoRight]
GO
